### ISSUE TITLE
Missing defaults support

### ISSUE THREAD

**Issue by CatchABus** [developit/redaxios#92] opened 2022-11-21 14:31 UTC
This package seems to be missing axios defaults support.
Even default instance makes use of them.

Example:
```js
import axios from "axios";

axios.defaults.baseURL = "/myurl";
```
Axios has these defaults right here: https://github.com/axios/axios/blob/v1.x/lib/defaults/index.js#L59

**Comment by rschristian** [comment] 2022-11-30 12:36
Duplicate of #62

**Closed as completed** 2023-01-10 17:47 UTC
Labels: duplicate
